platform :ios, '8.0'
use_frameworks!

def app
    pod 'Alamofire', '~> 4.3.0'
    pod 'SwiftyJSON', '~> 3.1.4'
end

target 'Webhose' do
    app
end

target 'WebhoseTests' do
    pod 'OHHTTPStubs'
    pod 'Quick'
    pod 'Nimble'
    app
end
