platform :ios, '8.0'
use_frameworks!

def app
    pod 'Alamofire'
    pod 'SwiftyJSON'
end

target 'Webhose' do
    app
end

target 'WebhoseTests' do
    pod 'OHHTTPStubs'
    pod 'Quick'
    pod 'Nimble'
    app
end
